import { Task } from '../types/task'

const mockTasks: Task[] = [
  {
    id: 1,
    title: "Fix authentication bug",
    priority: "High",
    dueDate: "2025-01-18",
    status: "In Progress",
    userId: 1,
  },
  {
    id: 2,
    title: "Add dashboard feature",
    priority: "Medium",
    dueDate: "2025-01-19",
    status: "To Do",
    userId: 2,
  },
  {
    id: 3,
    title: "Update API documentation",
    priority: "Low",
    dueDate: "2025-01-20",
    status: "Completed",
    userId: 3,
  },
  {
    id: 4,
    title: "Resolve database performance issues",
    priority: "High",
    dueDate: "2025-01-21",
    status: "In Progress",
    userId: 4,
  },
  {
    id: 5,
    title: "Prepare release notes",
    priority: "Low",
    dueDate: "2025-01-22",
    status: "To Do",
    userId: 5,
  },
  {
    id: 6,
    title: "Implement new authentication method",
    priority: "High",
    dueDate: "2025-01-23",
    status: "To Do",
    userId: 6,
  },
  {
    id: 7,
    title: "Write unit tests for API",
    priority: "Medium",
    dueDate: "2025-01-24",
    status: "In Progress",
    userId: 7,
  },
  {
    id: 8,
    title: "Optimize frontend rendering",
    priority: "High",
    dueDate: "2025-01-25",
    status: "To Do",
    userId: 8,
  },
  {
    id: 9,
    title: "Fix authentication bug",
    priority: "High",
    dueDate: "2025-01-18",
    status: "In Progress",
    userId: 1,
  },
  {
    id: 10,
    title: "Add dashboard feature",
    priority: "Medium",
    dueDate: "2025-01-19",
    status: "To Do",
    userId: 2,
  },
  {
    id: 11,
    title: "Update API documentation",
    priority: "Low",
    dueDate: "2025-01-20",
    status: "Completed",
    userId: 3,
  },
  {
    id: 12,
    title: "Resolve database performance issues",
    priority: "High",
    dueDate: "2025-01-21",
    status: "In Progress",
    userId: 4,
  },
  {
    id: 13,
    title: "Prepare release notes",
    priority: "Low",
    dueDate: "2025-01-22",
    status: "To Do",
    userId: 5,
  },
  {
    id: 14,
    title: "Implement new authentication method",
    priority: "High",
    dueDate: "2025-01-23",
    status: "To Do",
    userId: 6,
  },
  {
    id: 15,
    title: "Write unit tests for API",
    priority: "Medium",
    dueDate: "2025-01-24",
    status: "In Progress",
    userId: 7,
  },
  {
    id: 16,
    title: "Optimize frontend rendering",
    priority: "High",
    dueDate: "2025-01-25",
    status: "To Do",
    userId: 8,
  },
  {
    id: 17,
    title: "Fix authentication bug",
    priority: "High",
    dueDate: "2025-01-18",
    status: "In Progress",
    userId: 1,
  },
  {
    id: 18,
    title: "Add dashboard feature",
    priority: "Medium",
    dueDate: "2025-01-19",
    status: "To Do",
    userId: 2,
  },
  {
    id: 19,
    title: "Update API documentation",
    priority: "Low",
    dueDate: "2025-01-20",
    status: "Completed",
    userId: 3,
  },
  {
    id: 20,
    title: "Resolve database performance issues",
    priority: "High",
    dueDate: "2025-01-21",
    status: "In Progress",
    userId: 4,
  },
  {
    id: 21,
    title: "Prepare release notes",
    priority: "Low",
    dueDate: "2025-01-22",
    status: "To Do",
    userId: 5,
  },
  {
    id: 22,
    title: "Implement new authentication method",
    priority: "High",
    dueDate: "2025-01-23",
    status: "To Do",
    userId: 6,
  },
  {
    id: 23,
    title: "Write unit tests for API",
    priority: "Medium",
    dueDate: "2025-01-24",
    status: "In Progress",
    userId: 7,
  },
  {
    id: 24,
    title: "Optimize frontend rendering",
    priority: "High",
    dueDate: "2025-01-25",
    status: "To Do",
    userId: 8,
  },
  {
    id: 25,
    title: "Fix authentication bug",
    priority: "High",
    dueDate: "2025-01-18",
    status: "In Progress",
    userId: 1,
  },
  {
    id: 26,
    title: "Add dashboard feature",
    priority: "Medium",
    dueDate: "2025-01-19",
    status: "To Do",
    userId: 2,
  },
  {
    id: 27,
    title: "Update API documentation",
    priority: "Low",
    dueDate: "2025-01-20",
    status: "Completed",
    userId: 3,
  },
  {
    id: 28,
    title: "Resolve database performance issues",
    priority: "High",
    dueDate: "2025-01-21",
    status: "In Progress",
    userId: 4,
  },
  {
    id: 29,
    title: "Prepare release notes",
    priority: "Low",
    dueDate: "2025-01-22",
    status: "To Do",
    userId: 5,
  },
  {
    id: 30,
    title: "Implement new authentication method",
    priority: "High",
    dueDate: "2025-01-23",
    status: "To Do",
    userId: 6,
  },
  {
    id: 31,
    title: "Write unit tests for API",
    priority: "Medium",
    dueDate: "2025-01-24",
    status: "In Progress",
    userId: 7,
  },
  {
    id: 32,
    title: "Optimize frontend rendering",
    priority: "High",
    dueDate: "2025-01-25",
    status: "To Do",
    userId: 8,
  }


]

export default mockTasks;
